#!/usr/bin/env python3
"""Generate FILE-MAP.md — the directory index agents jump to instead of crawling.

Descriptions are pulled from what the code already declares (Go package doc
comments, Python module docstrings), so there is nothing extra to keep in sync:
change the package doc, regenerate, done. Directories with no such declaration
render an empty Purpose, which makes the undocumented corners visible rather
than inventing prose for them.

  python scripts/gen_file_map.py            # rewrite FILE-MAP.md
  python scripts/gen_file_map.py --check    # exit 1 if FILE-MAP.md is stale (CI)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "FILE-MAP.md"

# Trees worth mapping, in reading order. Everything else (node_modules, .venv,
# build output, caches) is deliberately absent — the map is for source.
ROOTS = ["cmd", "internal", "ingest", "bench", "web/src"]
SOURCE_SUFFIXES = {".go", ".py", ".ts", ".tsx"}
SKIP_DIR_PARTS = {"node_modules", "__pycache__", ".venv", "testdata", "dist"}

# Captures the package name too: "// Package bus is the Redis seam" -> "bus is
# the Redis seam", which reads as a sentence once "Package " is dropped.
GO_PKG_DOC = re.compile(r"^// Package (\w+ .+)$")


def _first_sentence(text, capitalize=True):
    text = " ".join(text.split())
    if not text:
        return ""
    # Keep it to one sentence so the table stays scannable.
    cut = re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0]
    return cut[:1].upper() + cut[1:] if capitalize else cut


def _go_doc(path):
    """First `// Package x <desc>` line found in a non-test .go file."""
    for f in sorted(path.glob("*.go")):
        if f.name.endswith("_test.go"):
            continue
        for line in f.read_text(encoding="utf-8", errors="replace").splitlines():
            m = GO_PKG_DOC.match(line.strip())
            if m:
                # Package names are lowercase by convention — don't capitalise.
                return _first_sentence(m.group(1), capitalize=False)
            if line.strip().startswith("package "):
                break  # past the doc block for this file
    return ""


def _py_doc(path):
    """Module docstring of the most substantial non-test .py file in the dir."""
    cands = [f for f in path.glob("*.py") if not f.name.startswith(("test_", "check_"))]
    for f in sorted(cands, key=lambda p: p.stat().st_size, reverse=True):
        src = f.read_text(encoding="utf-8", errors="replace")
        # Skip a shebang and any encoding/comment preamble: the docstring is
        # still the module docstring when `#!/usr/bin/env python3` precedes it.
        src = re.sub(r"\A(?:\s*#[^\n]*\n)+", "", src)
        m = re.match(r'\s*(?:"""|\'\'\')(.*?)(?:"""|\'\'\')', src, re.S)
        if m and m.group(1).strip():
            return _first_sentence(m.group(1).strip().splitlines()[0])
    return ""


def _ts_doc(path):
    """First `/** ... @packageDocumentation */` block in a .ts/.tsx file.

    TSDoc's @packageDocumentation is the direct analogue of Go's `// Package x`:
    it marks a comment as describing the whole module rather than the next
    symbol, so no convention had to be invented for the TypeScript trees.
    """
    for f in sorted([*path.glob("*.ts"), *path.glob("*.tsx")]):
        if ".test." in f.name:
            continue
        src = f.read_text(encoding="utf-8", errors="replace")
        m = re.match(r"\s*/\*\*(.*?)\*/", src, re.S)
        if m and "@packageDocumentation" in m.group(1):
            body = m.group(1).replace("@packageDocumentation", "")
            lines = [ln.strip().lstrip("*").strip() for ln in body.splitlines()]
            text = " ".join(ln for ln in lines if ln)
            if text:
                return _first_sentence(text)
    return ""


def _describe(path):
    if any(path.glob("*.go")):
        return _go_doc(path)
    if any(path.glob("*.py")):
        return _py_doc(path)
    return _ts_doc(path)


def _dirs():
    seen = []
    for r in ROOTS:
        base = ROOT / r
        if not base.is_dir():
            continue
        for d in sorted([base, *base.rglob("*")]):
            if not d.is_dir() or SKIP_DIR_PARTS & set(d.relative_to(ROOT).parts):
                continue
            n = len([f for f in d.iterdir() if f.is_file() and f.suffix in SOURCE_SUFFIXES])
            if n:
                seen.append((d.relative_to(ROOT).as_posix(), n, _describe(d)))
    return seen


def render():
    rows = _dirs()
    out = [
        "# FILE-MAP",
        "",
        "Generated by `scripts/gen_file_map.py` — **do not hand-edit.**",
        "Purpose comes from each package's own Go doc comment or Python module",
        "docstring, so it cannot drift from the code. Regenerate with",
        "`python scripts/gen_file_map.py`; CI fails if this file is stale.",
        "",
        "A blank Purpose means that directory declares no package doc or module",
        "docstring — an orientation gap, not an omission by the generator.",
        "",
        "| Directory | Source files | Purpose |",
        "| --- | ---: | --- |",
    ]
    for path, n, desc in rows:
        out.append(f"| `{path}` | {n} | {desc} |")
    out += ["", f"{len(rows)} source directories, "
            f"{sum(n for _, n, _ in rows)} files, "
            f"{sum(1 for _, _, d in rows if not d)} without a declared purpose.", ""]
    return "\n".join(out)


def main():
    text = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("FILE-MAP.md is stale - run: python scripts/gen_file_map.py")
            return 1
        print("FILE-MAP.md is current")
        return 0
    # newline="" keeps the LF endings built above intact on Windows, so the file
    # is byte-identical wherever it is generated and --check never trips on CRLF.
    with OUT.open("w", encoding="utf-8", newline="") as fh:
        fh.write(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
